// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA65naGC8J71U8DjX88V7MPJdSlLjkFWG4',
    appId: '1:104741099540:web:4c4255618c276c8dcbaf01',
    messagingSenderId: '104741099540',
    projectId: 'healthpocket-32bd8',
    authDomain: 'healthpocket-32bd8.firebaseapp.com',
    storageBucket: 'healthpocket-32bd8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhaNQJDmCvKzGEhD8nxtEtNJs9j_ukBNI',
    appId: '1:104741099540:android:31ed5c325e336a44cbaf01',
    messagingSenderId: '104741099540',
    projectId: 'healthpocket-32bd8',
    storageBucket: 'healthpocket-32bd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_cAPf72pmCjLDK7VkrqWqdGdzF9evnbU',
    appId: '1:104741099540:ios:637a8eb1ee6ff5e6cbaf01',
    messagingSenderId: '104741099540',
    projectId: 'healthpocket-32bd8',
    storageBucket: 'healthpocket-32bd8.firebasestorage.app',
    iosBundleId: 'olas.tykhonchuk.com.appka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_cAPf72pmCjLDK7VkrqWqdGdzF9evnbU',
    appId: '1:104741099540:ios:637a8eb1ee6ff5e6cbaf01',
    messagingSenderId: '104741099540',
    projectId: 'healthpocket-32bd8',
    storageBucket: 'healthpocket-32bd8.firebasestorage.app',
    iosBundleId: 'olas.tykhonchuk.com.appka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA65naGC8J71U8DjX88V7MPJdSlLjkFWG4',
    appId: '1:104741099540:web:36940140caa4dd5ecbaf01',
    messagingSenderId: '104741099540',
    projectId: 'healthpocket-32bd8',
    authDomain: 'healthpocket-32bd8.firebaseapp.com',
    storageBucket: 'healthpocket-32bd8.firebasestorage.app',
  );
}
